---
abstract: 'Run a subroutine'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-Runner
requires:
  Algorithm::Dependency: 0
  Capture::Tiny: 0
  File::Path: 2.08
  File::chdir: 0
  Log::Any: 0
  Moo: 0
  Sub::Spec: 0.08
  Test::More: 0.96
  YAML::Syck: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-Runner/
  repository: http://github.com/sharyanto/perl-Sub-Spec-Runner
version: 0.13
